# Generated by Django 2.2.6 on 2019-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_bossprofile_mystore'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='normalprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
