# Generated by Django 2.2.3 on 2019-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_bossprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalprofile',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to='profileimg/'),
        ),
    ]
