# Generated by Django 2.2.3 on 2019-10-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0009_auto_20191009_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='openhour',
            field=models.TextField(null=True),
        ),
    ]
