# Generated by Django 2.2.3 on 2019-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
