# Generated by Django 2.2.6 on 2019-10-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0016_stamp_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='level',
        ),
    ]
