# Generated by Django 2.2.6 on 2019-10-30 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0017_remove_stamp_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
