# Generated by Django 2.2.3 on 2019-11-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0019_auto_20191031_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='bookstore_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='name',
            field=models.CharField(default='storename', max_length=20, null=True),
        ),
    ]
