# Generated by Django 2.2.6 on 2019-11-04 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0020_auto_20191102_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='openhour_tf',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='openhour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
