# Generated by Django 2.2.6 on 2019-11-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0021_auto_20191104_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstore',
            options={'ordering': ['name']},
        ),
    ]
