# Generated by Django 2.2.3 on 2019-11-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0022_auto_20191107_1733'),
        ('bookmap', '0022_auto_20191107_1923'),
    ]

    operations = [
    ]
