# Generated by Django 2.2.6 on 2019-11-19 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0023_merge_20191111_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookstore',
            name='openhour_tf',
        ),
        migrations.AddField(
            model_name='bookstore',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='saup',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='000-00-00000 형식에 맞게 입력해주세요.', regex='^\\d{3}\\-\\d{2}\\-\\d{5}$')]),
        ),
    ]
