# Generated by Django 2.2.3 on 2019-11-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0025_auto_20191125_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bookstore',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='bookmap.Tag'),
        ),
    ]
