# Generated by Django 2.2.3 on 2019-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0026_auto_20191125_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
