# Generated by Django 2.2.3 on 2019-11-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0027_auto_20191125_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='thema/'),
        ),
    ]
