# Generated by Django 2.2.6 on 2019-11-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0028_tag_img'),
        ('bookmap', '0025_auto_20191125_1657'),
    ]

    operations = [
    ]
