# Generated by Django 2.2.3 on 2019-11-28 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0029_merge_20191126_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='000-0000-0000과 같은 형식으로 입력해주세요.', regex='^\\d{2,3}\\-\\d{3,4}\\-\\d{4}$')]),
        ),
    ]
