# Generated by Django 2.2.3 on 2019-12-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0029_merge_20191126_1520'),
        ('bookmap', '0029_merge_20191126_1458'),
    ]

    operations = [
    ]
