# Generated by Django 2.2.6 on 2019-11-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmap', '0029_merge_20191126_1458'),
        ('bookmap', '0030_auto_20191126_1627'),
        ('bookmap', '0029_merge_20191126_1520'),
    ]

    operations = [
    ]
