# Generated by Django 2.2.6 on 2019-10-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_auto_20191028_1950'),
        ('others', '0009_auto_20191029_1541'),
    ]

    operations = [
    ]
