# Generated by Django 2.2.3 on 2019-11-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_auto_20191031_1510'),
        ('others', '0010_merge_20191029_1900'),
    ]

    operations = [
    ]
