# Generated by Django 2.2.6 on 2019-10-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_merge_20191029_1900'),
        ('others', '0009_auto_20191031_1510'),
    ]

    operations = [
    ]
