# Generated by Django 2.2.6 on 2019-11-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_merge_20191031_1753'),
        ('others', '0011_merge_20191102_1832'),
    ]

    operations = [
    ]
