# Generated by Django 2.2.6 on 2019-11-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_merge_20191103_1224'),
        ('others', '0012_merge_20191103_1633'),
    ]

    operations = [
    ]
