# Generated by Django 2.2.6 on 2019-11-05 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0013_merge_20191104_1457'),
        ('others', '0013_merge_20191104_1453'),
        ('others', '0013_merge_20191104_1745'),
        ('others', '0013_merge_20191104_1442'),
    ]

    operations = [
    ]
